//
//  ClipboardMonitorCaptureDecisionTests.swift
//  MyPasteAppTests
//

import AppKit
import Testing

@testable import MyPasteApp

/// Covers the guard ordering inside `ClipboardMonitor.poll()`: pause wins
/// outright, then a privacy marker, and only once both are clear does
/// anything get captured. `poll()` itself can't be exercised directly (it's
/// private and hard-wired to `NSPasteboard.general`), so these tests target
/// the pure decision it delegates to instead.
@MainActor
@Suite("Clipboard monitor capture decision")
struct ClipboardMonitorCaptureDecisionTests {
    private let plainText = NSPasteboard.PasteboardType("public.utf8-plain-text")

    private var permissive: PasteboardPrivacy.Settings {
        PasteboardPrivacy.Settings(ignoreConcealed: true,
                                   ignoreTransient: true,
                                   ignoreAutoGenerated: false)
    }

    @Test("Paused with ordinary content is not captured")
    func pausedWithCleanTypesIsSkipped() {
        #expect(ClipboardMonitor.shouldCapture(isPaused: true,
                                               types: [plainText],
                                               settings: permissive) == false)
    }

    @Test("Unpaused content carrying a concealed marker is not captured")
    func unpausedWithConcealedMarkerIsSkipped() {
        #expect(ClipboardMonitor.shouldCapture(
            isPaused: false,
            types: [plainText, PasteboardPrivacy.concealed],
            settings: permissive) == false)
    }

    @Test("Unpaused ordinary content is captured")
    func unpausedWithCleanTypesIsCaptured() {
        #expect(ClipboardMonitor.shouldCapture(isPaused: false,
                                               types: [plainText],
                                               settings: permissive))
    }

    @Test("Paused and marked content is not captured")
    func pausedAndMarkedIsSkipped() {
        #expect(ClipboardMonitor.shouldCapture(
            isPaused: true,
            types: [plainText, PasteboardPrivacy.concealed],
            settings: permissive) == false)
    }

    // MARK: - Per-app rules (roadmap item 18)

    @Test("An app set to ignore everything is rejected before the pasteboard is read")
    func ignoredAppIsRejectedEarly() {
        // The point of this test is the *signature*, as much as the result:
        // this decision takes a bundle ID and nothing else, so it structurally
        // cannot come to depend on having read the content first. Before
        // Phase 5 the app check ran after readCurrentItem(), which meant a
        // banned app's content was read into memory and only then dropped.
        let rules = [AppRule(bundleID: "com.apple.Passwords", allowedTypes: [])]

        #expect(AppRules.ignoresEverything("com.apple.Passwords", rules: rules))
        #expect(AppRules.ignoresEverything("com.apple.Safari", rules: rules) == false)
    }

    @Test("A text-only app doesn't get its images stored")
    func typedRuleDropsOtherTypes() {
        let rules = [AppRule(bundleID: "com.tinyspeck.slackmacgap", allowedTypes: [.text])]

        #expect(AppRules.allows(type: .text, from: "com.tinyspeck.slackmacgap", rules: rules))
        #expect(AppRules.allows(type: .image, from: "com.tinyspeck.slackmacgap", rules: rules) == false)
    }

    @Test("Pause still wins over everything")
    func pauseStillWins() {
        // The guard order this suite exists to freeze: pause first, privacy
        // markers second, and only then anything app-specific.
        #expect(ClipboardMonitor.shouldCapture(isPaused: true,
                                               types: [plainText],
                                               settings: permissive) == false)
    }
}
