//
//  ClipboardMonitorCaptureDecisionTests.swift
//  MyPasteAppTests
//

import AppKit
import Testing

@testable import MyPasteApp

/// Covers the guard ordering inside `ClipboardMonitor.poll()`: pause wins
/// outright, then a privacy marker, and only once both are clear does
/// anything get captured. `poll()` itself can't be exercised directly (it's
/// private and hard-wired to `NSPasteboard.general`), so these tests target
/// the pure decision it delegates to instead.
@MainActor
@Suite("Clipboard monitor capture decision")
struct ClipboardMonitorCaptureDecisionTests {
    private let plainText = NSPasteboard.PasteboardType("public.utf8-plain-text")

    private var permissive: PasteboardPrivacy.Settings {
        PasteboardPrivacy.Settings(ignoreConcealed: true,
                                   ignoreTransient: true,
                                   ignoreAutoGenerated: false)
    }

    @Test("Paused with ordinary content is not captured")
    func pausedWithCleanTypesIsSkipped() {
        #expect(ClipboardMonitor.shouldCapture(isPaused: true,
                                               types: [plainText],
                                               settings: permissive) == false)
    }

    @Test("Unpaused content carrying a concealed marker is not captured")
    func unpausedWithConcealedMarkerIsSkipped() {
        #expect(ClipboardMonitor.shouldCapture(
            isPaused: false,
            types: [plainText, PasteboardPrivacy.concealed],
            settings: permissive) == false)
    }

    @Test("Unpaused ordinary content is captured")
    func unpausedWithCleanTypesIsCaptured() {
        #expect(ClipboardMonitor.shouldCapture(isPaused: false,
                                               types: [plainText],
                                               settings: permissive))
    }

    @Test("Paused and marked content is not captured")
    func pausedAndMarkedIsSkipped() {
        #expect(ClipboardMonitor.shouldCapture(
            isPaused: true,
            types: [plainText, PasteboardPrivacy.concealed],
            settings: permissive) == false)
    }
}
