//
//  PasteboardPrivacyTests.swift
//  MyPasteAppTests
//

import AppKit
import Testing

@testable import MyPasteApp

@Suite("Pasteboard privacy")
struct PasteboardPrivacyTests {
    private let defaults = TestDefaults("pasteboard-privacy")

    private let plainText = NSPasteboard.PasteboardType("public.utf8-plain-text")
    private let png = NSPasteboard.PasteboardType("public.png")

    private var allOn: PasteboardPrivacy.Settings {
        PasteboardPrivacy.Settings(ignoreConcealed: true,
                                   ignoreTransient: true,
                                   ignoreAutoGenerated: true)
    }

    private var allOff: PasteboardPrivacy.Settings {
        PasteboardPrivacy.Settings(ignoreConcealed: false,
                                   ignoreTransient: false,
                                   ignoreAutoGenerated: false)
    }

    // MARK: - Defaults

    @Test("Concealed and transient are ignored out of the box, auto-generated isn't")
    func defaultSettings() {
        // A missed copy costs far less than a password in the history — but
        // "machine-generated" is too broad to discard uninvited.
        let settings = PasteboardPrivacy.Settings.current(from: defaults.store)
        #expect(settings.ignoreConcealed)
        #expect(settings.ignoreTransient)
        #expect(settings.ignoreAutoGenerated == false)
    }

    @Test("Stored flags are honoured")
    func storedSettings() {
        defaults.store.set(false, forKey: "ignoreConcealedContent")
        defaults.store.set(false, forKey: "ignoreTransientContent")
        defaults.store.set(true, forKey: "ignoreAutoGeneratedContent")

        let settings = PasteboardPrivacy.Settings.current(from: defaults.store)
        #expect(settings.ignoreConcealed == false)
        #expect(settings.ignoreTransient == false)
        #expect(settings.ignoreAutoGenerated)
    }

    // MARK: - Decision

    @Test("Ordinary content is never ignored")
    func ordinaryContentIsKept() {
        #expect(PasteboardPrivacy.shouldIgnore(types: [plainText], settings: allOn) == false)
        #expect(PasteboardPrivacy.shouldIgnore(types: [png], settings: allOn) == false)
        #expect(PasteboardPrivacy.shouldIgnore(types: [], settings: allOn) == false)
    }

    @Test("A marked type is ignored when its toggle is on")
    func markedTypesAreIgnored() {
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [plainText, PasteboardPrivacy.concealed], settings: allOn))
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [plainText, PasteboardPrivacy.transient], settings: allOn))
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [plainText, PasteboardPrivacy.autoGenerated], settings: allOn))
    }

    @Test("A marked type is kept when its toggle is off")
    func markedTypesAreKeptWhenDisabled() {
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [plainText, PasteboardPrivacy.concealed], settings: allOff) == false)
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [plainText, PasteboardPrivacy.transient], settings: allOff) == false)
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [plainText, PasteboardPrivacy.autoGenerated], settings: allOff) == false)
    }

    @Test("Each toggle only governs its own type")
    func togglesAreIndependent() {
        let concealedOnly = PasteboardPrivacy.Settings(ignoreConcealed: true,
                                                       ignoreTransient: false,
                                                       ignoreAutoGenerated: false)
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [PasteboardPrivacy.concealed], settings: concealedOnly))
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [PasteboardPrivacy.transient], settings: concealedOnly) == false)
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [PasteboardPrivacy.autoGenerated], settings: concealedOnly) == false)
    }

    @Test("With several markers present, any enabled one is enough")
    func anyEnabledMarkerWins() {
        let transientOnly = PasteboardPrivacy.Settings(ignoreConcealed: false,
                                                       ignoreTransient: true,
                                                       ignoreAutoGenerated: false)
        #expect(PasteboardPrivacy.shouldIgnore(
            types: [PasteboardPrivacy.concealed, PasteboardPrivacy.transient],
            settings: transientOnly))
    }

    @Test("The marker identifiers follow the nspasteboard.org convention")
    func typeIdentifiers() {
        // These strings are a contract with other apps; a typo would silently
        // disable the whole feature.
        #expect(PasteboardPrivacy.concealed.rawValue == "org.nspasteboard.ConcealedType")
        #expect(PasteboardPrivacy.transient.rawValue == "org.nspasteboard.TransientType")
        #expect(PasteboardPrivacy.autoGenerated.rawValue == "org.nspasteboard.AutoGeneratedType")
    }
}
