//
//  PreferenceKeysTests.swift
//  MyPasteAppTests
//

import Testing

@testable import MyPasteApp

/// Freezes the on-disk names of every preference key.
///
/// These strings are a storage format, not an implementation detail: renaming
/// one makes every existing installation silently fall back to its default,
/// with no crash and no failing build to catch it. Changing a value here means
/// changing what users already have on disk, so this test is meant to be hard
/// to update by accident.
@Suite("Preference keys")
struct PreferenceKeysTests {
    @Test("Key names never change")
    func keysAreFrozen() {
        #expect(PreferenceKeys.maxItems == "maxItems")
        #expect(PreferenceKeys.retentionDays == "retentionDays")
        #expect(PreferenceKeys.previewTextLength == "previewTextLength")
        #expect(PreferenceKeys.enableSoundFeedback == "enableSoundFeedback")
        #expect(PreferenceKeys.ignoredAppsRaw == "ignoredAppsRaw")
        #expect(PreferenceKeys.autoPasteEnabled == "autoPasteEnabled")
        #expect(PreferenceKeys.pasteDelayMs == "pasteDelayMs")
        #expect(PreferenceKeys.showLinkPreviews == "showLinkPreviews")
        #expect(PreferenceKeys.cardDensity == "cardDensity")
        #expect(PreferenceKeys.showQuickPasteNumbers == "showQuickPasteNumbers")
        #expect(PreferenceKeys.showInScreenSharing == "showInScreenSharing")
        #expect(PreferenceKeys.ignoreConcealedContent == "ignoreConcealedContent")
        #expect(PreferenceKeys.ignoreTransientContent == "ignoreTransientContent")
        #expect(PreferenceKeys.ignoreAutoGeneratedContent == "ignoreAutoGeneratedContent")
        #expect(PreferenceKeys.alwaysPastePlainText == "alwaysPastePlainText")
        #expect(PreferenceKeys.enableImageOCR == "enableImageOCR")
        #expect(PreferenceKeys.multiPasteSeparator == "multiPasteSeparator")
        #expect(PreferenceKeys.appRules == "appRules")
    }

    @Test("No two keys collide")
    func keysAreUnique() {
        let all = PreferenceKeys.all
        #expect(Set(all).count == all.count)
    }
}
