//
//  PrivacySettingsView.swift
//  MyPasteApp
//

import SwiftUI

struct PrivacySettingsView: View {
    @AppStorage(PreferenceKeys.showInScreenSharing) private var showInScreenSharing: Bool = false
    @AppStorage(PreferenceKeys.ignoreConcealedContent) private var ignoreConcealedContent: Bool = true
    @AppStorage(PreferenceKeys.ignoreTransientContent) private var ignoreTransientContent: Bool = true
    @AppStorage(PreferenceKeys.ignoreAutoGeneratedContent) private var ignoreAutoGeneratedContent: Bool = false
    @AppStorage(PreferenceKeys.ignoredAppsRaw) private var ignoredAppsRaw: String = ""

    var body: some View {
        Form {
            Section {
                SettingsToggle(
                    title: "Show during screen sharing",
                    description: "When off, the overlay and this window don't appear in screen sharing or recordings — including screenshots you take yourself.",
                    isOn: $showInScreenSharing
                )
            }
            Section("Marked content") {
                Toggle("Ignore confidential content", isOn: $ignoreConcealedContent)
                Toggle("Ignore transient content", isOn: $ignoreTransientContent)
                Toggle("Ignore auto-generated content", isOn: $ignoreAutoGeneratedContent)
                Text("Apps can mark what they copy as a password, as throwaway data or as machine-generated. This only works when the source app marks it — and many don't, including Apple's own Passwords app. Those have to be listed below.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Section("Ignored apps") {
                TextEditor(text: $ignoredAppsRaw)
                    .font(.system(.body, design: .monospaced))
                    .frame(minHeight: 60, maxHeight: 100)
                    .overlay(
                        RoundedRectangle(cornerRadius: 4)
                            .stroke(Color.secondary.opacity(0.3))
                    )
                Text("One bundle ID per line. Nothing copied from these apps is ever recorded — this is the only protection that doesn't depend on the app marking its own content.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                Text("Worth adding: com.apple.Passwords · com.apple.keychainaccess")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .textSelection(.enabled)
            }
        }
        .formStyle(.grouped)
    }
}
