//
//  PrivacySettingsView.swift
//  MyPasteApp
//

import SwiftUI

struct PrivacySettingsView: View {
    @AppStorage(PreferenceKeys.showInScreenSharing) private var showInScreenSharing: Bool = false
    @AppStorage(PreferenceKeys.ignoreConcealedContent) private var ignoreConcealedContent: Bool = true
    @AppStorage(PreferenceKeys.ignoreTransientContent) private var ignoreTransientContent: Bool = true
    @AppStorage(PreferenceKeys.ignoreAutoGeneratedContent) private var ignoreAutoGeneratedContent: Bool = false
    @AppStorage(PreferenceKeys.enableImageOCR) private var enableImageOCR: Bool = true

    var body: some View {
        Form {
            Section {
                SettingsToggle(
                    title: "Show during screen sharing",
                    description: "When off, the overlay and this window don't appear in screen sharing or recordings — including screenshots you take yourself.",
                    isOn: $showInScreenSharing
                )
            }
            Section {
                SettingsToggle(
                    title: "Recognise text in images",
                    description: "Makes text inside screenshots searchable. Recognition happens on this Mac — nothing is uploaded. Turning it off stops new images from being processed and keeps what was already recognised.",
                    isOn: $enableImageOCR
                )
            }
            Section("Marked content") {
                Toggle("Ignore confidential content", isOn: $ignoreConcealedContent)
                Toggle("Ignore transient content", isOn: $ignoreTransientContent)
                Toggle("Ignore auto-generated content", isOn: $ignoreAutoGeneratedContent)
                Text("Apps can mark what they copy as a password, as throwaway data or as machine-generated. This only works when the source app marks it — and many don't, including Apple's own Passwords app. Those have to be listed below.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Section("App rules") {
                AppRulesListView()
            }
        }
        .formStyle(.grouped)
    }
}
