//
//  PreferencesView.swift
//  MyPasteApp
//

import AppKit
import ServiceManagement
import SwiftData
import SwiftUI

struct PreferencesView: View {
    @Environment(\.modelContext) private var modelContext
    @AppStorage("maxItems") private var maxItems: Int = 500
    @AppStorage("retentionDays") private var retentionDays: Int = 30
    @AppStorage("enableSoundFeedback") private var enableSoundFeedback: Bool = true
    @AppStorage("ignoredAppsRaw") private var ignoredAppsRaw: String = ""
    @AppStorage("autoPasteEnabled") private var autoPasteEnabled: Bool = true
    @AppStorage("pasteDelayMs") private var pasteDelayMs: Int = 50
    @AppStorage("previewTextLength") private var previewTextLength: Int = 200
    @AppStorage("showLinkPreviews") private var showLinkPreviews: Bool = true
    @AppStorage("cardDensity") private var cardDensity: String = CardDensity.comfortable.rawValue
    @AppStorage("showQuickPasteNumbers") private var showQuickPasteNumbers: Bool = true
    @AppStorage("showInScreenSharing") private var showInScreenSharing: Bool = false
    @AppStorage("ignoreConcealedContent") private var ignoreConcealedContent: Bool = true
    @AppStorage("ignoreTransientContent") private var ignoreTransientContent: Bool = true
    @AppStorage("ignoreAutoGeneratedContent") private var ignoreAutoGeneratedContent: Bool = false
    @State private var launchAtLogin: Bool = SMAppService.mainApp.status == .enabled
    @State private var hotkey: KeyCombo = KeyCombo.stored
    @State private var pauseHotkey: KeyCombo = KeyCombo.storedPause
    @State private var hotkeyConflict = false

    var body: some View {
        Form {
            Section("History") {
                Stepper("Max items: \(maxItems)",
                        value: $maxItems, in: 50...5000, step: 50)
                Stepper("Retain for: \(retentionDays) days",
                        value: $retentionDays, in: 1...365)
                Stepper("Preview text length: \(previewTextLength)",
                        value: $previewTextLength, in: 80...500, step: 20)
                Toggle("Sound on copy", isOn: $enableSoundFeedback)
                Button("Clear non-pinned history") {
                    clearHistory()
                }
            }
            Section("Global shortcuts") {
                HStack {
                    Text("Show/hide overlay")
                    Spacer()
                    HotkeyRecorderView(combo: $hotkey)
                        .frame(width: 160, height: 24)
                    Button("Reset") {
                        hotkey = .default
                    }
                }
                HStack {
                    Text("Pause/resume capture")
                    Spacer()
                    HotkeyRecorderView(combo: $pauseHotkey)
                        .frame(width: 160, height: 24)
                    Button("Reset") {
                        pauseHotkey = .pauseDefault
                    }
                }
                if hotkeyConflict {
                    Text("Both shortcuts can't use the same combination.")
                        .font(.caption)
                        .foregroundStyle(.red)
                }
                Text("Click the field and press a new shortcut. Esc cancels.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            .onChange(of: hotkey) { _, newValue in
                applyHotkeyChange(new: newValue,
                                  other: pauseHotkey,
                                  key: KeyCombo.storageKey,
                                  fallback: .default) { hotkey = $0 }
            }
            .onChange(of: pauseHotkey) { _, newValue in
                applyHotkeyChange(new: newValue,
                                  other: hotkey,
                                  key: KeyCombo.pauseStorageKey,
                                  fallback: .pauseDefault) { pauseHotkey = $0 }
            }
            Section("Appearance") {
                Picker("Card density", selection: $cardDensity) {
                    ForEach(CardDensity.allCases) { d in
                        Text(d.label).tag(d.rawValue)
                    }
                }
                Toggle("Show link previews", isOn: $showLinkPreviews)
                Toggle("Show quick paste numbers", isOn: $showQuickPasteNumbers)
                Text("⌘1–⌘9 paste the first nine visible cards. The shortcuts keep working with the numbers hidden.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Section("Paste behavior") {
                Toggle("Auto-paste on selection (simulate ⌘V)", isOn: $autoPasteEnabled)
                Stepper("Paste delay: \(pasteDelayMs) ms",
                        value: $pasteDelayMs, in: 0...500, step: 10)
                    .disabled(!autoPasteEnabled)
                Text("Increase the delay if some apps drop the simulated ⌘V.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Section("Privacy") {
                Toggle("Show during screen sharing", isOn: $showInScreenSharing)
                Text("When off, the overlay and this window don't appear in screen sharing or recordings — including screenshots you take yourself.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                Divider()
                Toggle("Ignore confidential content", isOn: $ignoreConcealedContent)
                Toggle("Ignore transient content", isOn: $ignoreTransientContent)
                Toggle("Ignore auto-generated content", isOn: $ignoreAutoGeneratedContent)
                Text("Apps can mark what they copy as a password, as throwaway data or as machine-generated. This only works when the source app marks it, so it complements the list below instead of replacing it.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                Divider()
                VStack(alignment: .leading, spacing: 6) {
                    Text("Ignore content from these apps")
                    TextEditor(text: $ignoredAppsRaw)
                        .font(.system(.body, design: .monospaced))
                        .frame(minHeight: 60, maxHeight: 100)
                        .overlay(
                            RoundedRectangle(cornerRadius: 4)
                                .stroke(Color.secondary.opacity(0.3))
                        )
                    Text("One bundle ID per line (e.g. com.agilebits.onepassword7).")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }
            Section("Startup") {
                Toggle("Launch at login", isOn: $launchAtLogin)
                    .onChange(of: launchAtLogin) { _, newValue in
                        toggleLaunchAtLogin(newValue)
                    }
            }
        }
        .formStyle(.grouped)
        .frame(minWidth: 460, minHeight: 640)
        .onAppear {
            refreshHotkeyState()
        }
    }

    /// Reconciles the two @State copies with what's actually persisted and
    /// recomputes whether they collide, instead of trusting whatever
    /// `hotkeyConflict` happened to be left at.
    ///
    /// The window is created once and cached (see `AppDelegate.openPreferences`),
    /// so this view's `@State` — and a stale `hotkeyConflict = true` along with
    /// it — would otherwise survive every close and reopen even after the
    /// field that caused it was already reverted. Re-deriving it here also
    /// surfaces a collision that existed before this window ever opened, e.g.
    /// the pause shortcut falling back to a default that already collides
    /// with the overlay one at launch (see `AppDelegate.registerHotkeysCheckingConflict`).
    private func refreshHotkeyState() {
        hotkey = KeyCombo.stored
        pauseHotkey = KeyCombo.storedPause
        hotkeyConflict = KeyCombo.conflicts(hotkey, with: pauseHotkey)
    }

    private func clearHistory() {
        let descriptor = FetchDescriptor<ClipboardItem>(
            predicate: #Predicate { !$0.isPinned }
        )
        if let items = try? modelContext.fetch(descriptor) {
            for item in items { modelContext.delete(item) }
            try? modelContext.save()
        }
    }

    private func toggleLaunchAtLogin(_ enabled: Bool) {
        do {
            if enabled {
                try SMAppService.mainApp.register()
            } else {
                try SMAppService.mainApp.unregister()
            }
        } catch {
            NSLog("Failed to toggle launch at login: \(error)")
        }
    }

    /// Saves a re-recorded shortcut, or refuses it when it would collide with
    /// the other one — `RegisterEventHotKey` would otherwise leave one of them
    /// silently dead.
    ///
    /// Stateless by design: rather than a flag to swallow the extra
    /// `onChange` that reverting triggers — which stays dropped, and silently
    /// eats the next legitimate change, if the two writes it depends on ever
    /// get coalesced into one SwiftUI update — this treats "already what's
    /// persisted" as nothing to do. Reverting sets the `@State` back to that
    /// same persisted value, so the extra `onChange` it fires takes this same
    /// early return without any flag to track across the two independent
    /// handlers.
    private func applyHotkeyChange(new: KeyCombo,
                                   other: KeyCombo,
                                   key: String,
                                   fallback: KeyCombo,
                                   revert: (KeyCombo) -> Void) {
        let persisted = KeyCombo.load(key: key, fallback: fallback)
        guard new != persisted else { return }
        if KeyCombo.conflicts(new, with: other) {
            NSSound.beep()
            hotkeyConflict = true
            revert(persisted)
            return
        }
        hotkeyConflict = false
        KeyCombo.save(new, key: key)
    }
}
