//
//  PasteboardPrivacy.swift
//  MyPasteApp
//
//  Honours the nspasteboard.org convention: apps that copy sensitive or
//  throwaway content mark it with an auxiliary type, asking clipboard
//  managers not to record it.
//
//  It only works when the source app cooperates, so this complements the
//  ignored-apps list rather than replacing it.
//

import AppKit
import Foundation

enum PasteboardPrivacy {
    /// Written by password managers when copying a secret.
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    /// Written by automations using the pasteboard as a temporary channel.
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    /// Machine-produced content.
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    struct Settings: Equatable {
        var ignoreConcealed: Bool
        var ignoreTransient: Bool
        var ignoreAutoGenerated: Bool

        /// Concealed and transient default to on — the cost of a missed copy
        /// is much lower than that of a password in the history. Auto-generated
        /// defaults to off: it is broad enough that some apps mark content the
        /// user did mean to copy.
        static func current(from defaults: UserDefaults = .standard) -> Settings {
            Settings(
                ignoreConcealed: defaults.object(forKey: PreferenceKeys.ignoreConcealedContent) as? Bool ?? true,
                ignoreTransient: defaults.object(forKey: PreferenceKeys.ignoreTransientContent) as? Bool ?? true,
                ignoreAutoGenerated: defaults.object(forKey: PreferenceKeys.ignoreAutoGeneratedContent) as? Bool ?? false
            )
        }
    }

    /// Takes the types present on the pasteboard rather than the pasteboard
    /// itself, so the rule can be tested without touching the system one.
    static func shouldIgnore(types: [NSPasteboard.PasteboardType],
                             settings: Settings) -> Bool {
        if settings.ignoreConcealed, types.contains(concealed) { return true }
        if settings.ignoreTransient, types.contains(transient) { return true }
        if settings.ignoreAutoGenerated, types.contains(autoGenerated) { return true }
        return false
    }
}
