//
//  PreferenceKeys.swift
//  MyPasteApp
//

import Foundation

/// The `UserDefaults` keys the app reads and writes.
///
/// These values are a storage format. Renaming one doesn't break the build or
/// any behaviour that a test would notice — it just makes every existing
/// installation fall back to defaults, losing the user's configuration in
/// silence. `PreferenceKeysTests` freezes them for that reason.
///
/// `KeyCombo` keeps its own two keys (`KeyCombo.storageKey` and
/// `KeyCombo.pauseStorageKey`): they're already named constants next to the
/// type that owns their format, and moving them here would only add a hop.
enum PreferenceKeys {
    static let maxItems = "maxItems"
    static let retentionDays = "retentionDays"
    static let previewTextLength = "previewTextLength"
    static let enableSoundFeedback = "enableSoundFeedback"
    static let ignoredAppsRaw = "ignoredAppsRaw"
    static let autoPasteEnabled = "autoPasteEnabled"
    static let pasteDelayMs = "pasteDelayMs"
    static let showLinkPreviews = "showLinkPreviews"
    static let cardDensity = "cardDensity"
    static let showQuickPasteNumbers = "showQuickPasteNumbers"
    static let showInScreenSharing = "showInScreenSharing"
    static let ignoreConcealedContent = "ignoreConcealedContent"
    static let ignoreTransientContent = "ignoreTransientContent"
    static let ignoreAutoGeneratedContent = "ignoreAutoGeneratedContent"

    /// Forces every paste to plain text, regardless of what was captured.
    /// Off by default: the app should hand back what it was given.
    static let alwaysPastePlainText = "alwaysPastePlainText"

    static let all: [String] = [
        maxItems, retentionDays, previewTextLength, enableSoundFeedback,
        ignoredAppsRaw, autoPasteEnabled, pasteDelayMs, showLinkPreviews,
        cardDensity, showQuickPasteNumbers, showInScreenSharing,
        ignoreConcealedContent, ignoreTransientContent,
        ignoreAutoGeneratedContent, alwaysPastePlainText,
    ]
}
